# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/classificationWdg.ui'
#
# Created: Mon Aug  4 18:03:56 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ClassificationWdg(object):
    def setupUi(self, ClassificationWdg):
        ClassificationWdg.setObjectName(_fromUtf8("ClassificationWdg"))
        ClassificationWdg.resize(430, 641)
        self.verticalLayout = QtGui.QVBoxLayout(ClassificationWdg)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_3 = QtGui.QGroupBox(ClassificationWdg)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.addClassBtn = QtGui.QToolButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addClassBtn.sizePolicy().hasHeightForWidth())
        self.addClassBtn.setSizePolicy(sizePolicy)
        self.addClassBtn.setObjectName(_fromUtf8("addClassBtn"))
        self.gridLayout_3.addWidget(self.addClassBtn, 0, 1, 1, 2)
        self.classesTable = QtGui.QTableView(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classesTable.sizePolicy().hasHeightForWidth())
        self.classesTable.setSizePolicy(sizePolicy)
        self.classesTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.classesTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.classesTable.setObjectName(_fromUtf8("classesTable"))
        self.classesTable.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.classesTable, 0, 0, 3, 1)
        self.delClassBtn = QtGui.QToolButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delClassBtn.sizePolicy().hasHeightForWidth())
        self.delClassBtn.setSizePolicy(sizePolicy)
        self.delClassBtn.setObjectName(_fromUtf8("delClassBtn"))
        self.gridLayout_3.addWidget(self.delClassBtn, 1, 1, 1, 2)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(ClassificationWdg)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.drawAreaBtn = QtGui.QToolButton(self.groupBox_2)
        self.drawAreaBtn.setCheckable(True)
        self.drawAreaBtn.setObjectName(_fromUtf8("drawAreaBtn"))
        self.gridLayout_2.addWidget(self.drawAreaBtn, 0, 0, 1, 1)
        self.clearAreaBtn = QtGui.QToolButton(self.groupBox_2)
        self.clearAreaBtn.setObjectName(_fromUtf8("clearAreaBtn"))
        self.gridLayout_2.addWidget(self.clearAreaBtn, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(ClassificationWdg)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.addBufferBtn = QtGui.QToolButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addBufferBtn.sizePolicy().hasHeightForWidth())
        self.addBufferBtn.setSizePolicy(sizePolicy)
        self.addBufferBtn.setCheckable(True)
        self.addBufferBtn.setObjectName(_fromUtf8("addBufferBtn"))
        self.gridLayout.addWidget(self.addBufferBtn, 0, 1, 1, 2)
        self.buffersTable = QtGui.QTableView(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buffersTable.sizePolicy().hasHeightForWidth())
        self.buffersTable.setSizePolicy(sizePolicy)
        self.buffersTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.buffersTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.buffersTable.setObjectName(_fromUtf8("buffersTable"))
        self.buffersTable.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.buffersTable, 0, 0, 9, 1)
        self.delBufferBtn = QtGui.QToolButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delBufferBtn.sizePolicy().hasHeightForWidth())
        self.delBufferBtn.setSizePolicy(sizePolicy)
        self.delBufferBtn.setObjectName(_fromUtf8("delBufferBtn"))
        self.gridLayout.addWidget(self.delBufferBtn, 1, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem, 2, 1, 2, 1)
        self.crossSectionBtn = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crossSectionBtn.sizePolicy().hasHeightForWidth())
        self.crossSectionBtn.setSizePolicy(sizePolicy)
        self.crossSectionBtn.setObjectName(_fromUtf8("crossSectionBtn"))
        self.gridLayout.addWidget(self.crossSectionBtn, 4, 1, 2, 2)
        self.polygonSectionBtn = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polygonSectionBtn.sizePolicy().hasHeightForWidth())
        self.polygonSectionBtn.setSizePolicy(sizePolicy)
        self.polygonSectionBtn.setObjectName(_fromUtf8("polygonSectionBtn"))
        self.gridLayout.addWidget(self.polygonSectionBtn, 6, 1, 3, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.displayClassifiedDataBtn = QtGui.QPushButton(ClassificationWdg)
        self.displayClassifiedDataBtn.setObjectName(_fromUtf8("displayClassifiedDataBtn"))
        self.verticalLayout.addWidget(self.displayClassifiedDataBtn)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(ClassificationWdg)
        QtCore.QMetaObject.connectSlotsByName(ClassificationWdg)

    def retranslateUi(self, ClassificationWdg):
        ClassificationWdg.setWindowTitle(QtGui.QApplication.translate("ClassificationWdg", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ClassificationWdg", "Polygon classes (\"_\" index separator)", None, QtGui.QApplication.UnicodeUTF8))
        self.addClassBtn.setText(QtGui.QApplication.translate("ClassificationWdg", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.delClassBtn.setText(QtGui.QApplication.translate("ClassificationWdg", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ClassificationWdg", "Define area of interest", None, QtGui.QApplication.UnicodeUTF8))
        self.drawAreaBtn.setText(QtGui.QApplication.translate("ClassificationWdg", "Draw", None, QtGui.QApplication.UnicodeUTF8))
        self.clearAreaBtn.setText(QtGui.QApplication.translate("ClassificationWdg", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ClassificationWdg", "Classification buffers", None, QtGui.QApplication.UnicodeUTF8))
        self.addBufferBtn.setText(QtGui.QApplication.translate("ClassificationWdg", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.delBufferBtn.setText(QtGui.QApplication.translate("ClassificationWdg", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.crossSectionBtn.setText(QtGui.QApplication.translate("ClassificationWdg", "Open the \n"
"cross section", None, QtGui.QApplication.UnicodeUTF8))
        self.polygonSectionBtn.setText(QtGui.QApplication.translate("ClassificationWdg", "Open the \n"
"polygon section", None, QtGui.QApplication.UnicodeUTF8))
        self.displayClassifiedDataBtn.setText(QtGui.QApplication.translate("ClassificationWdg", "Update classified earthquakes", None, QtGui.QApplication.UnicodeUTF8))

