# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filterWdg.ui'
#
# Created: Mon Jul  2 13:22:53 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_FilterWdg(object):
    def setupUi(self, FilterWdg):
        FilterWdg.setObjectName(_fromUtf8("FilterWdg"))
        FilterWdg.resize(238, 394)
        self.verticalLayout = QtGui.QVBoxLayout(FilterWdg)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(FilterWdg)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.magnitudeRangeFilter = DoubleRangeFilter(self.groupBox)
        self.magnitudeRangeFilter.setObjectName(_fromUtf8("magnitudeRangeFilter"))
        self.gridLayout.addWidget(self.magnitudeRangeFilter, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(FilterWdg)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.depthRangeFilter = RangeFilter(self.groupBox_2)
        self.depthRangeFilter.setObjectName(_fromUtf8("depthRangeFilter"))
        self.gridLayout_2.addWidget(self.depthRangeFilter, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(FilterWdg)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.dateRangeFilter = DateRangeFilter(self.groupBox_3)
        self.dateRangeFilter.setObjectName(_fromUtf8("dateRangeFilter"))
        self.gridLayout_3.addWidget(self.dateRangeFilter, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_5 = QtGui.QGroupBox(FilterWdg)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.drawPolygonBtn = QtGui.QToolButton(self.groupBox_5)
        self.drawPolygonBtn.setCheckable(True)
        self.drawPolygonBtn.setObjectName(_fromUtf8("drawPolygonBtn"))
        self.horizontalLayout.addWidget(self.drawPolygonBtn)
        self.clearPolygonBtn = QtGui.QToolButton(self.groupBox_5)
        self.clearPolygonBtn.setObjectName(_fromUtf8("clearPolygonBtn"))
        self.horizontalLayout.addWidget(self.clearPolygonBtn)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.line = QtGui.QFrame(FilterWdg)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.groupBox_4 = QtGui.QGroupBox(FilterWdg)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.plotTypeCombo = QtGui.QComboBox(self.groupBox_4)
        self.plotTypeCombo.setObjectName(_fromUtf8("plotTypeCombo"))
        self.gridLayout_4.addWidget(self.plotTypeCombo, 0, 1, 1, 2)
        self.label = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.xAxisCombo = QtGui.QComboBox(self.groupBox_4)
        self.xAxisCombo.setObjectName(_fromUtf8("xAxisCombo"))
        self.gridLayout_4.addWidget(self.xAxisCombo, 1, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 2, 0, 1, 1)
        self.yAxisCombo = QtGui.QComboBox(self.groupBox_4)
        self.yAxisCombo.setObjectName(_fromUtf8("yAxisCombo"))
        self.gridLayout_4.addWidget(self.yAxisCombo, 2, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 3, 0, 1, 1)
        self.titleEdit = QtGui.QLineEdit(self.groupBox_4)
        self.titleEdit.setObjectName(_fromUtf8("titleEdit"))
        self.gridLayout_4.addWidget(self.titleEdit, 3, 1, 1, 1)
        self.plotBtn = QtGui.QToolButton(self.groupBox_4)
        self.plotBtn.setObjectName(_fromUtf8("plotBtn"))
        self.gridLayout_4.addWidget(self.plotBtn, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)

        self.retranslateUi(FilterWdg)
        QtCore.QMetaObject.connectSlotsByName(FilterWdg)
        FilterWdg.setTabOrder(self.drawPolygonBtn, self.clearPolygonBtn)
        FilterWdg.setTabOrder(self.clearPolygonBtn, self.plotTypeCombo)
        FilterWdg.setTabOrder(self.plotTypeCombo, self.xAxisCombo)
        FilterWdg.setTabOrder(self.xAxisCombo, self.yAxisCombo)
        FilterWdg.setTabOrder(self.yAxisCombo, self.titleEdit)
        FilterWdg.setTabOrder(self.titleEdit, self.plotBtn)

    def retranslateUi(self, FilterWdg):
        FilterWdg.setWindowTitle(QtGui.QApplication.translate("FilterWdg", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("FilterWdg", "Magnitude", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("FilterWdg", "Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("FilterWdg", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("FilterWdg", "Spatial", None, QtGui.QApplication.UnicodeUTF8))
        self.drawPolygonBtn.setText(QtGui.QApplication.translate("FilterWdg", "Draw", None, QtGui.QApplication.UnicodeUTF8))
        self.clearPolygonBtn.setText(QtGui.QApplication.translate("FilterWdg", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("FilterWdg", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FilterWdg", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FilterWdg", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("FilterWdg", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("FilterWdg", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.plotBtn.setText(QtGui.QApplication.translate("FilterWdg", "Plot", None, QtGui.QApplication.UnicodeUTF8))

from rangeFilter import DateRangeFilter, DoubleRangeFilter, RangeFilter
